name: 🛡️ API Doc Change
description: Create an issue to add or update the API documentation.
title: "API Doc Change - "
labels: ['🛡️api-doc-changes', 'high-priority']
type: "Feature"
projects: ["KinsonDigital/11"]
body:
- type: checkboxes
  attributes:
    label: Complete The Item Below
    options:
    - label: I have added the version to the very end of the issue title.
      required: true

- type: textarea
  attributes:
    label: Description
    description: A description of the change to the documentation.
  validations:
    required: true

- type: textarea
  attributes:
    label: Acceptance Criteria
    description: The items to complete in order to satisfy the Definition of Done.
    placeholder: |
      - [ ] Item 1
      - [ ] Item 2
    value: |
      - [ ] If adding a new version of the API documentation, I have locally executed the documentation processing scripts to generate new API documentation.
      - [ ] If adding a new version of the API documentation, I have used the correct [Velaptor version](https://github.com/KinsonDigital/Velaptor/tags).
      - [ ] Any documentation changes have been checked for proper spelling and grammar.
  validations:
    required: true
    render: markdown

- type: textarea
  attributes:
    label: ToDo Items
    description: Complete the following items before requesting a PR review.
    value: |
      - [ ] The oldest version is removed with a remaining maximum of 5 versions.
  validations:
    required: true
    render: markdown

- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/KinsonDigital/.github/blob/main/docs/code_of_conduct.md).
    options:
      - label: I agree to follow this project's Code of Conduct.
        required: true
