name: ⚙️ Other Changes
description: Create an issue for non documentation related changes.
title: "⚙️"
projects: ["KinsonDigital/11"]
body:
- type: checkboxes
  attributes:
    label: Complete The Item Below
    options:
    - label: I have updated the title without removing the ⚙️ emoji.
      required: true

- type: textarea
  attributes:
    label: Description
    description: A description of the change to the documentation.
  validations:
    required: true

- type: textarea
  attributes:
    label: Acceptance Criteria
    description: The items to complete in order to satisfy the Definition of Done.
    placeholder: |
      ```[tasklist]
      - [ ] Item 1
      - [ ] Item 2
      ```
    value: |
      ```[tasklist]
      ```
  validations:
    required: true
    render: markdown

- type: textarea
  attributes:
    label: ToDo items
    description: Complete the following items before requesting a PR review.
    value: |
      ```[tasklist]
      - [ ] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
      - [ ] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
      ```
  validations:
    required: true
    render: markdown

- type: textarea
  attributes:
    label: "Additional Information:"
    description: DO NOT CHANGE ANYTHING BELOW!!
    value: |
      **_<details closed><summary>Change Type Labels</summary>_**
      
      |--------------|---------------------------------------------------------------------------------------------------|
      | CICD                 | https://github.com/KinsonDigital/VelaptorDocs/labels/cicd                                 |
      | Dependency Update    | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%A6dependency-update        |
      | Miscellaneous        | https://github.com/KinsonDigital/VelaptorDocs/labels/miscellaneous                        |
      | Guide Doc Changes | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%9Cguide-doc-changes           |
      </details>

      **_<details closed><summary>Priority Type Labels</summary>_**
      
      | Priority Type       | Label                                                                  |
      |---------------------|------------------------------------------------------------------------|
      | Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low-priority    |
      | Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium-priority |
      | High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high-priority   |
      </details>

- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/KinsonDigital/.github/blob/main/docs/code_of_conduct.md).
    options:
      - label: I agree to follow this project's Code of Conduct.
        required: true
