name: 📜 Tutorial Documentation Change
description: Create an issue to add or update tutorial documentation.
title: "📜"
labels: ['📜tutorial doc changes']
projects: ["KinsonDigital/11"]
body:
- type: checkboxes
  attributes:
    label: Complete The Item Below
    options:
    - label: I have updated the title without removing the 📜 emoji.
      required: true

- type: textarea
  attributes:
    label: Description
    description: A description of the change to the documentation.
  validations:
    required: true

- type: textarea
  attributes:
    label: Acceptance Criteria
    placeholder: |
      Example:
        - [ ] Item 1 complete
        - [ ] Item 2 complete
    description: The items to complete in order to satisfy the Definition of Done.
  validations:
    required: true
    render: markdown

- type: checkboxes
  attributes:
    label: ToDo Items
    description: Complete the following items before requesting a PR review.
    options:
    - label: Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
    - label: Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.

- type: textarea
  attributes:
    label: "Additional Information:"
    description: DO NOT CHANGE ANYTHING BELOW!!
    value: |
      **_<details closed><summary>Priority Type Labels</summary>_**
      
      | Priority Type       | Label                                                                  |
      |---------------------|------------------------------------------------------------------------|
      | Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low%20priority    |
      | Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium%20priority |
      | High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high%20priority   |
      </details>

- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/KinsonDigital/.github/blob/master/docs/CODE_OF_CONDUCT.md).
    options:
      - label: I agree to follow this project's Code of Conduct.
        required: true
