name: ✅CICD Build Status Check (FORK)
run-name: ✅CICD Build Status Check (FORK)


defaults:
  run:
    shell: pwsh


on:
  pull_request:
    branches: main


jobs:
  cicd_build_status_check_fork:
    name: CICD Build Status Check (FORK)
    runs-on: ubuntu-latest
    steps:
    - name: Detect Fork
      id: detect_fork
      run: |
        if ("${{ github.event.pull_request.head.repo.full_name }}" -ne "${{ github.event.pull_request.base.repo. full_name }}") {
          echo "is_fork=true" >> $env:GITHUB_OUTPUT;
        } else {
          echo "is_fork=false" >> $env:GITHUB_OUTPUT;
        }

    - uses: actions/checkout@v4
      if: steps.detect_fork.outputs.is_fork == 'true'

    - name: Setup Deno (v1.46.x)
      if: steps.detect_fork.outputs.is_fork == 'true'
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.46.x

    - name: Run Build
      if: steps.detect_fork.outputs.is_fork == 'true'
      run: deno task build;
